app = "tradingview-hyperliquid-bot"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
